# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ETL_To_Target.py
#   (generated by ArcGIS/ModelBuilder)
# Description: Append from the London source database to the target gdb
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("C:/Users/Steve/Documents/GitHub/geo-London/gzTools/Gizinta.tbx")


# Local variables:
ETL_LONDON_gdb = "C:\\Users\\Steve\\Documents\\GitHub\\geo-London\\content\\data\\ETL_LONDON_SOURCE.gdb"
ETL_LONDON_TARGET_gdb = "C:\\Users\\Steve\\Documents\\GitHub\\geo-London\\content\\data\\ETL_LONDON.gdb"
success = "true"

# Process: replaceRowsGDB
arcpy.replaceRowsGDB_gizinta(ETL_LONDON_gdb, ETL_LONDON_TARGET_gdb, "")

