# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# UpdateRoadSType.py
# Created on: 2017-08-28 10:55:58.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Roads__3_ = "C:\\Users\\Steve\\Documents\\GitHub\\geo-London\\content\\data\\ETL_LONDON_TARGET.gdb\\Roads"
Roads__4_ = Roads__3_
Roads = "C:\\Users\\Steve\\Documents\\GitHub\\geo-London\\content\\data\\ETL_LONDON_TARGET.gdb\\Roads"
Roads__2_ = Roads

# Process: Calculate Field
arcpy.CalculateField_management(Roads, "SType", "updateSType(!Subtype!)", "PYTHON", "def updateSType(Subtype):\\n  stype = ''\\n  if Subtype == 1:\\n    stype = 'Public'\\n  elif Subtype == 2:\\n    stype = 'Private'\\n  elif Subtype == 3:\\n    stype = 'Constructed'\\n\\n  return stype\\n")

# Process: Delete Field
arcpy.DeleteField_management(Roads__3_, "Subtype")

