# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# UpdateRoadsTopoData.py
# Created on: 2017-08-28 11:45:41.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Archive the current roads data and append new data to current feature class
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Roads_Topo20170430 = "C:\\Users\\Steve\\Documents\\GitHub\\geo-London\\content\\data\\ETL_LONDON_SOURCE.gdb\\Roads_Topo20170430"
Roads__2_ = Roads_Topo20170430
Roads = "C:\\Users\\Steve\\Documents\\GitHub\\geo-London\\content\\data\\ETL_LONDON.gdb\\Roads"
Roads__3_ = Roads
Roads_Archive2017 = "C:\\Users\\Steve\\Documents\\GitHub\\geo-London\\content\\data\\ETL_LONDON.gdb\\Roads_Archive2017"

# Process: Copy
arcpy.Copy_management(Roads, Roads_Archive2017, "FeatureClass")

# Process: Delete Rows
arcpy.DeleteRows_management(Roads)

# Process: Append
arcpy.Append_management("C:\\Users\\Steve\\Documents\\GitHub\\geo-London\\content\\data\\ETL_LONDON_SOURCE.gdb\\Roads_Topo20170430", Roads__3_, "TEST", "", "")

